spring.application.name=studentdata
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=sql30
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
